export default {
  splashBackground: '#E1F5FF',
  dullBackground: '#666666',
  background: '#FFFFFF',
  primary: '#49ACE3',
  subText: '#7D7B7B',
  tertiaryText: '#E6E6E6',
  quadText: '#808080',
  placeholderText: '#AAAAAA',
  buttonText: '#FFFFFF',
  sliderThumb: '#ECF8F9',
  slider: '#F0F0F0',
  sliderBottomText: '#939191',
  crossBackground: '#EB5757',
  placeholder: '#F9F9F9',
  switchOn: '#C9E4FB',
  componentBackground1: '#F5F5FF',
  componentBackground2: '#EDF8FE',
  componentBackground3: '#FCF1EF',
  componentBackground4: '#FFFBF4',
  calendarBackground: '#FFFFFF',
  reminderInternal: '#F5FBFF',
  AMContainer: '#E0F3FC',
  statCSides: '#EBEBEC',
  VisualizerContainer: '#F8FDFF',
  disabled: '#9DA2A5',
  splashText: '#3695E8',
  progressUnfilled: '#DBF3FE',

  // reused #FFFFFF
};
