export default {
  arrowRight: require('../assets/icons/arrow.png'),
  glass: require('../assets/icons/glass.png'),
  cloudMasked: require('../assets/icons/cloudMasked.png'),
  maleAvatar: require('../assets/icons/male-avatar.png'),
  womenAvatar: require('../assets/icons/woman-avatar.png'),
  chevronDown: require('../assets/icons/chevron-down.png'),
  cross: require('../assets/icons/cross.png'),
  menu: require('../assets/icons/Group-2.png'),
  arrowsRight: require('../assets/icons/arrows3.png'),
  anatomy: require('../assets/icons/anatomy.png'),
  plus: require('../assets/icons/plus.png'),
  clock: require('../assets/icons/clock.png'),
  calendar: require('../assets/icons/calendar.png'),
  arrowBack: require('../assets/icons/arrow-back.png'),
  logo: require('../assets/icons/logo.png'),
  bell: require('../assets/icons/bell.png'),
  stats: require('../assets/icons/stats.png'),
  reset: require('../assets/icons/reset.png'),
  rate: require('../assets/icons/rate.png'),
  flag: require('../assets/icons/flag.png'),
  clockBlue: require('../assets/icons/clockblue.png'),
  edit: require('../assets/icons/edit.png'),
  alarmIcon: require('../assets/icons/alarmIcon.png'),
  splashLogo: require('../assets/icons/splashlogo.png'),
};
